name: CD pipline
on:
    workflow_run:
        workflows: "React CI/CD"
        types: 
            - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prectice

    steps:

      - name: "Set-up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'
        
      - name: "setup vercal CLI"
        run: npm i -g vercel 

      - name: "Download build artifact"
        uses: actions/download-artifact@v4
        with:
            name: build-artifact
      - name: build
        run: ${{ github.event.workspace_run.id }}

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.Vercel_Token }} -- confirm
          