name: CD pipline
on:
    workflow_run:
        workflows: "React CI/CD"
        types: 
            - completed
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prectice

    steps:

      - name: "Set-up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'
        
      - name: "setup vercal CLI"
        run: npm i -g vercel 

      - name: "Downlord build files"
        uses: actions/download-artifact@v4
        with:
            name: build
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm

          